### ISSUE TITLE
Salam - Missing information from orphan packs

### ISSUE THREAD

**Issue by shakeebqayum** [n3oltd/N3O.Umbraco#271]
The 'Cause of Death' and 'Guardian Relation' under Father Details and 'Accommodation Type'  information seem to be missing from orphan packs when downloading or the pack is sent to the donor. The details are filled in on Umbraco.

Have regenerated packs but same issue.

See example orphan OR10235 from Lebanon Sponsorship SP1000767.

![Image](https://user-images.githubusercontent.com/133132640/240979891-0d288618-1ba6-45d8-8f21-48fc0fdf3e62.png)

![Image](https://user-images.githubusercontent.com/133132640/240980171-d9bb7c3f-858f-4ceb-9599-023a3a35e7d1.png)

![Image](https://user-images.githubusercontent.com/133132640/240980344-cd99595c-3aef-4908-9af0-e1ef6fe63265.png)

**Comment by talhamalik4025** [comment]
@shakeebqayum Fixed
