### ISSUE TITLE
Extend cart to support allocations linked to pages (including messages of support)

### ISSUE THREAD

**Issue by nadrummond** [n3oltd/N3O.Umbraco#383]
Whether clients will be embedding the crowd funding in an existing site or running it standalone, we will in both cases be using the existing cart/checkout. We therefore need to extend the `Allocation` object so that it can contain information about the page it was donated on (ID of page), any comments, whether the name of the donor is shown etc. This is so this can be stored in the cart.

At the conclusion of checkout we will need to add a hook that scans the cart for any allocations related to crowd funding and inserts these into the appropriate SQL table.

**Comment by talhamalik4025** [comment]
This was done
